# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr: none
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
   targetType: inline
   script: |
      ls
      Publish-Module -Path . -NuGetApiKey $(NUGETAPI)
  env:
    NEWGETAPI: $(NUGETAPI)