name: Publish PowerShell Module

on:
  release:
    types: ["published"]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path ./ps-copyid/ -NuGetApiKey $env:NUGET_KEY -Repository PSGallery